### ISSUE TITLE
Im not liking the look of recent activity from russia on google analytics

### ISSUE THREAD

**Issue by cpc157** [MehMenCo/MehMenCo.github.io#18]
sunday, monday, tuesday and wednesday they have been on the website. we put a block before this, does someone wanna check it out?

**Comment by j3456** [comment]
It's gonna be funny when we find out the Russian activity is just Mike's mum...

**Comment by donkeyguy** [comment]
Thu, Sun (<- Last Week)(Next Week ->), Mon, Tue, Wed
only 1 or 2 sessions tho, and only 1 unique user
.......................for now...............

**Comment by donkeyguy** [comment]
https://www.google.com/analytics/web/?hl=en#report/visitors-geo/a60939904w95511104p99648015/%3FtabControl.tabId%3Dgeo%26geo-segmentExplorer.segmentId%3Danalytics.country%26_r.drilldown%3Danalytics.country%3ARU%26geo-table.secSegmentId%3Danalytics.date%26geo-table.plotKeys%3D%5B%5D/

**Comment by mehmenmike** [comment]
Hmm. I'll keep an eye on them. They're blocked, so they shouldn't be able to do any harm. Maybe that's just the connection attempts coming through.

**Comment by mehmenmike** [comment]
Yeah, average session duration 00:00:00

**Comment by cpc157** [comment]
k cool i wasnt sure but thought might as well make sure you are aware
