### ISSUE TITLE
http://strawpoll.me/3968098

### ISSUE THREAD

**Issue by mehmenmike** [MehMenCo/MehMenCo.github.io#20]
http://strawpoll.me/3968098http://strawpoll.me/3968098
http://strawpoll.me/3968098

**Comment by donkeyguy** [comment]
its done now anyway, whats wrong with it?

**Comment by cpc157** [comment]
well people on our website might find it suspicious

**Comment by cpc157** [comment]
i wanna keep a rick roll somewhere tho

**Comment by cpc157** [comment]
# keep it

**Comment by j3456** [comment]
Actually we need to get rid of it, I am getting a "System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters." in the github desktop app

**Comment by j3456** [comment]
Or at least make it shorter
